name: druid-cluster
version: 0.1.0
appVersion: 0.21.1
description: Helm chart to deploy a druid cluster on Kubernetes
keywords:
- druid
- zookeeper
- postgres
maintainers:
- name: druid-operator-maintainers
sources:
- https://github.com/druid-io/druid-operator
engine: gotpl
home: https://github.com/druid-io/druid-operator
dependencies:
- name: zookeeper
  version: 10.0.0
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
